# Deployment Pipeline for the Bricks Bucket API.
image: monogum/docfx-surge:latest
pipelines:
    branches:
        master:
        - step:
            name: Build and Deploy to Production
            deployment: Production
            script:
            - git submodule update --init
            - docfx docfx.json
            - surge --project ./_site --domain $DOMAIN