# Deployment Pipeline for the Bricks Bucket API.
image: monogum/docfx-surge:latest

pipelines:
  default:
    - step:
        name: Build and Deploy to Production
        deployment: Production
        script:
          - docfx docfx.json
          - surge --project ./_site --domain $DOMAIN